### ISSUE TITLE
java.lang.NoSuchMethodError results in internal server error on registration attempt

### ISSUE THREAD

**Issue by atomicthumbs** [wadahiro/keycloak-discord#51]
I got this set up, but whenever users try to register, we get an internal server error. This occurs both with 0.5.0 and building from source. Stack trace:

```
keycloak  | 2024-10-07 04:07:06,438 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-5) Uncaught server error: java.lang.NoSuchMethodError: 'void org.keycloak.broker.provider.BrokeredIdentityContext.<init>(java.lang.String)'
keycloak  | 	at org.keycloak.social.discord.DiscordIdentityProvider.extractIdentityFromProfile(DiscordIdentityProvider.java:70)
keycloak  | 	at org.keycloak.social.discord.DiscordIdentityProvider.doGetFederatedIdentity(DiscordIdentityProvider.java:97)
keycloak  | 	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider.getFederatedIdentity(AbstractOAuth2IdentityProvider.java:314)
keycloak  | 	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:557)
keycloak  | 	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint$quarkusrestinvoker$authResponse_ab908fbdd086ee82e140d8a818c077362a2d04b4.invoke(Unknown Source)
keycloak  | 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak  | 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak  | 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
keycloak  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
keycloak  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
keycloak  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak  | 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by jhuesser** [comment]
I have the same issue on version 23.0.7

**Comment by AntiApple4life** [comment]
I'm also having this issue
